1# Write your MySQL query statement below
2SELECT
3        DATE_FORMAT(TRANS_DATE, '%Y-%m') AS MONTH,
4        COUNTRY,
5        COUNT(*) AS TRANS_COUNT,
6        SUM(STATE = 'APPROVED') AS APPROVED_COUNT,
7        SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,
8        SUM(IF(STATE = 'APPROVED', AMOUNT, 0)) AS APPROVED_TOTAL_AMOUNT
9FROM TRANSACTIONS
10GROUP BY MONTH, COUNTRY;