1# Write your MySQL query statement below
2SELECT 
3        SELL_DATE,
4        COUNT(DISTINCT PRODUCT) AS NUM_SOLD,
5        GROUP_CONCAT(DISTINCT PRODUCT ORDER BY PRODUCT SEPARATOR ',') AS PRODUCTS
6FROM ACTIVITIES
7GROUP BY SELL_DATE
8ORDER BY SELL_DATE;