1# Write your MySQL query statement below
2SELECT 
3        PERSON_NAME
4FROM (
5    SELECT
6        PERSON_NAME,
7        TURN,
8        SUM(WEIGHT) OVER(ORDER BY TURN) AS TOTAL_WEIGHT
9        FROM QUEUE
10) Q
11WHERE TOTAL_WEIGHT <= 1000
12ORDER BY TOTAL_WEIGHT DESC
13LIMIT 1;